# name = input("Enter your full name: ")
phone_number = input("Enter your phone #: ")
# result = (len(name))
# result = name.find("a")
# result = name.rfind("a")
# result = name.capitalize()
# result = name.upper()
# result = name.lower()
# result = name.isdigit()
# result = name.isalpha()
# result = phone_number.count("-")
result = phone_number.replace("-","")
print(result)